
print ("Brenner")
print ("Brenner")
print ("Brenner")
print ("Brenner")
print ("Brenner")
print ("Brenner")
print ("Brenner")
print ("Brenner")
print ("Brenner")
print ("Brenner")
print ("Brenner")
print ("Brenner")
